name: Java CI with Gradle

on: [ workflow_dispatch, push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Clean and Build with Gradle
        run: ./gradlew clean build
      - uses: actions/upload-artifact@v4
        with:
          name: NovenaInjector
          path: build/libs/